data "nutanix_virtual_machine" "virtual-machine" {}
data "nutanix_virtual_machines" "virtual-machines" {}
data "nutanix_image" "image" {}
data "nutanix_images" "images" {}
data "nutanix_subnet" "subnet" {}
data "nutanix_subnets" "subnets" {}
data "nutanix_clusters" "clusters" {}
data "nutanix_network_security_rule" "security-rule" {}
data "nutanix_network_security_rules" "security-rules" {}
data "nutanix_cluster" "cluster" {}
data "nutanix_volume_group" "volume-group" {}
data "nutanix_volume_groups" "volume-groups" {}